spring.application.name = demo

server.port = 8080

bot.name = AutoBot

bot.token = 6957853883:AAHKv1y1jV-liOIAQkvAlxszsRjTzFPAB0M

spring.datasource.driver-class-name = com.mysql.cj.jdbc.Driver

spring.datasource.username = root

spring.datasource.password = vadcristal2005

spring.datasource.url = jdbc:mysql://localhost:3306/chatbot

spring.jpa.hibernate.ddl-auto = update

spring.jpa.open-in-view = true

spring.jpa.show-sql = true